apiVersion: v1
appVersion: "1.0.0-rc9"
version: 0.7.0
kubeVersion: ">=1.11.0-0"
name: helm-operator
description: Flux Helm Operator is a CRD controller for declarative helming
home: https://fluxcd.io
sources:
- https://github.com/fluxcd/helm-operator
maintainers:
  - name: stefanprodan
    email: stefan@weave.works
engine: gotpl
icon: https://raw.githubusercontent.com/fluxcd/flux/master/docs/_files/weave-flux.png
keywords:
  - gitops
  - helm
